apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: giraffe
spec:
  cidr: 192.168.0.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: company == "giraffe"
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: zebra
spec:
  cidr: 192.168.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: company == "zebra"