apiVersion: v1
kind: Namespace
metadata:
  name: secretapp

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: values
  namespace: secretapp
data:
  react_app_username: "Kelad"
  react_app_company_name: "Giraffe"

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: secretapp
  namespace: secretapp
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: secretapp
  template:
    metadata:
      labels:
        tier: secretapp
    spec:
      containers:
      - name: secretapp
        image: ifilyaninitmo/itdt-contained-frontend:master
        env:
        - name: REACT_APP_USERNAME
          valueFrom:
            configMapKeyRef:
              name: values
              key: react_app_username
        - name: REACT_APP_COMPANY_NAME
          valueFrom:
            configMapKeyRef:
              name: values
              key: react_app_company_name

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  namespace: secretapp
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIFvzCCA6egAwIBAgIUMjRqR4jbUnoA/ICFD21Q3t9isC4wDQYJKoZIhvcNAQEL
    BQAwbzELMAkGA1UEBhMCUlUxDDAKBgNVBAgMA0FCQzEMMAoGA1UEBwwDQ0JBMQww
    CgYDVQQKDANBQUExDDAKBgNVBAsMA0JCQjEWMBQGA1UEAwwNc2VjcmV0YXBwLmNv
    bTEQMA4GCSqGSIb3DQEJARYBZjAeFw0yMzA5MjMxMjQ2MThaFw0yNDA5MjIxMjQ2
    MThaMG8xCzAJBgNVBAYTAlJVMQwwCgYDVQQIDANBQkMxDDAKBgNVBAcMA0NCQTEM
    MAoGA1UECgwDQUFBMQwwCgYDVQQLDANCQkIxFjAUBgNVBAMMDXNlY3JldGFwcC5j
    b20xEDAOBgkqhkiG9w0BCQEWAWYwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIK
    AoICAQDv+qxkEo553lyvfAsoCiy43XTTpSfPXLJcgfCzMUAI4WjUogebH0TVm8ex
    RbVSuG+Ln/Oj7fdNzn1UjdNNIfPOGVI+yFkdpbAqo3//ONfzfcUaYL+VipmtERIx
    ggjWQVb2RhTnYiBde9lw5j+GUDYQwbcfGeo9d7JRPr69q3YLNGzF3XrdrjL6PiUh
    6HsPczKt6LEeEtCaFKEY40epealic70t2SsJP9sEKcFfFkgHscass1wGwb3Kq5GI
    uwTAwAOr06kgKQw9jOOgeoeRltLR+yVlYgKs6kSE8xCx/s/MX02IyLTOJF8hadZG
    NTXdHgAChB59WYGHbwQ3fvCsLHZcowtd+7KHIsh49UDWCUzuwWhd5xOaMwxzBwJF
    S7iYxXOGfyxjLWfOTFP5NF/EK6I4FRLh9IbmAig1BTyFTf9YDvFfpcQ6CNX28tJw
    Hsykf2rfg0c4DAXpMMkkx+xB/nlIIk9CeUo/gEHizKnCIIehCTdjlYawVqlOC9w0
    yaKLPPYU2sZtlizZrDvYLw2CbVRWUwn4cGm+wfjT9nyG01cyy0CCunABMg0dm8U1
    qg+s0+oglkgnTW8+BPJdHKrIPP2GnXh5C5T044p9JCmOpHwkazL/gX51pX5V7QaT
    /QF0qaKCfE1WUK40Yz39eLyApyLFTcxPT36yDk06+GJt6qcccQIDAQABo1MwUTAd
    BgNVHQ4EFgQUB1IyV7d5fdWK/eFNkOrf4dfbut4wHwYDVR0jBBgwFoAUB1IyV7d5
    fdWK/eFNkOrf4dfbut4wDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
    AgEA7C6GUxek2jI8eh9HW8mdxZ64DQkHBaOXsm7EfYUZ4Y0lePLlKomAJ/b2PIVf
    bizfef6b8W5r3j8AsFAgOUyqprFHtc6KqfMlgeie3OaItNKfrQ98VI+fAbPUBg6e
    waVAev1cRAQf8LLO1dBW1w84gYRFKdzm7VN+dHqp+8v/01p0EaFQX96S/JdjxN3w
    2wMAH8k2AkgCUKCIR0uiYjvk92VPaZzt+a2nCyMMrKmtnenWV8Q6BZAWaaoBGmST
    B1uwUtblcZpFDOK6b+YmEmeRdgVZJ2Qj6qn0x9T3bXFFK/iGtXpqCNPG77RtPdBY
    EZjD1RAFLkbSB9ukhGlQcwloq86nygBNsMFjTL5yjxchqleBElZCj1VIev5m1Kpv
    u8kNWgqunZfVxbqxp9a1IEpY1h8kxNQsHJICiiOYZM2CotKCmYnca9uDZj6dziGD
    HbNKSfnhLziJ5UsTNeQBT2zqIuPRdGOyFoinAByj8j7PQzqpfkD8jlFJI440BglG
    muuhwoJciv9KKIrnOLw2gvV/6Qydatax906IWAN+s4bAV8Ok/1N81aQ7lMzB7cec
    O4MilS57x8i0dpQCNg9bqYWgwhLBN3mZPhBJYQNkz8KGwqzHyVvRm4adfEdx7Wb8
    nT79Wj1Gj4HqPnIa+pNbLxwZjPzuYKXT2z/Ufp5mD4jQnsU=
    -----END CERTIFICATE----- 
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQDv+qxkEo553lyv
    fAsoCiy43XTTpSfPXLJcgfCzMUAI4WjUogebH0TVm8exRbVSuG+Ln/Oj7fdNzn1U
    jdNNIfPOGVI+yFkdpbAqo3//ONfzfcUaYL+VipmtERIxggjWQVb2RhTnYiBde9lw
    5j+GUDYQwbcfGeo9d7JRPr69q3YLNGzF3XrdrjL6PiUh6HsPczKt6LEeEtCaFKEY
    40epealic70t2SsJP9sEKcFfFkgHscass1wGwb3Kq5GIuwTAwAOr06kgKQw9jOOg
    eoeRltLR+yVlYgKs6kSE8xCx/s/MX02IyLTOJF8hadZGNTXdHgAChB59WYGHbwQ3
    fvCsLHZcowtd+7KHIsh49UDWCUzuwWhd5xOaMwxzBwJFS7iYxXOGfyxjLWfOTFP5
    NF/EK6I4FRLh9IbmAig1BTyFTf9YDvFfpcQ6CNX28tJwHsykf2rfg0c4DAXpMMkk
    x+xB/nlIIk9CeUo/gEHizKnCIIehCTdjlYawVqlOC9w0yaKLPPYU2sZtlizZrDvY
    Lw2CbVRWUwn4cGm+wfjT9nyG01cyy0CCunABMg0dm8U1qg+s0+oglkgnTW8+BPJd
    HKrIPP2GnXh5C5T044p9JCmOpHwkazL/gX51pX5V7QaT/QF0qaKCfE1WUK40Yz39
    eLyApyLFTcxPT36yDk06+GJt6qcccQIDAQABAoICAAtCz8A8Ke8EcQRb0XTz+cZk
    v3K/SDGEBbtfLlelSO5FwA7iydE019y/dDDgjtY6cQML+uGLVRCTzwgmxdajsEpw
    gB5RtdNVIyG0FYl5HhKXKTawOatDc0vGjlxQABjIPQO+VQSo01CZs0HXzx0vEkNp
    6K07IMWYwl+LPoV9WFMlJxHHn2hrwEkDfaf0PiKS5vrXzYhmDP9+9nKJ10L30lvM
    JzFhpIIpCr6stC4RaEjCpgpUeg333U9nasNQFdRy6jUv3+rCPFieze9p0obhnUPU
    2XvS/CHHtjaIJqVYmgEKy5NOqkPWW3ewnQlDPdNiARF9KEZc6u3rVucBBBuLNFRU
    HfO/lx93OhUfQ/0jpbjurTMd1hGunkhhLb9+Onwv5HQGDikPOKlUR9SGF6zmEYQQ
    BGhqHrdGtGL83kSI9sDJY3GidBnMLYilGBvdHJ+zDbJupdW8YfG91Xzas3tI3A+w
    kYWN5n2/h/M8S41PgW6NZE06kBn8KRR1zrYGyZpYZ/WF1Jwl+trcuQ2emCztsUaA
    3aq8g8fuItH7Ki3nhBZy7TzniwnnI20fgMOMCwYl28zlCWZ31o3UMupozqHkJiQ1
    OwB0UptVst1CxfW846+6TRW+UjODkoVNU+G3PjTdG5LQ/ZcmdbSxX2FpjDGRSaPq
    7pPtECpPIaGt51+lPkphAoIBAQD+dFdwjJrGqmvPtoryfJsMwJxT/MT1gABTuaqT
    rXhtytMi7xBsnvaND26eQc8OJ45FR8SW0hFLZAuRaKaHlxPHNw+wMPHP64mBrvF0
    xIRCMxn5MfFYaLyA+iaNtl2A7xa6WA6HN85mQYrelTQ6fzLEy6rF2QPs6O9wkDGJ
    eGUiyWFhWyLwK4TA8nAsEIzfLJVSIr4hC2gH1D1Wj+WpJ+vMAIKh4/3k+AV94Ehc
    ixRVkYYmuJcTZGgvQXhnTPpMyJpg9xH4cJPRtX2NM32dvS2MauJ5tD4yCzMUYOJV
    +MpRUZkTWJ9GnkiQbyXFSyP11tiVK22RmhZMXONNW6YLKp3hAoIBAQDxb9LnKe9j
    0ZAl88/9434MdLQUtxdHUoATFMVcxh6GxgkNvGaPLH3T/hY1Ocme82mvdKwEZrMp
    uPRxBdxfdompjmOXrYOf6EMnam6lvuh6KSiLZeGZjIaiYHoNVcf+IKbSHrkVplEd
    BfIHpLKFXJx2GR+01LSd5exVPl06Bmp3HI1zEjZbBfWtQFXg2Bc+VsUuEcsLigaC
    DropGgHUqw2UIEB2HhAjGFRQHs7ssHmkCKMbTzHkVLCNQQFIuZG1fxl6v79BNltq
    NbBt4LKwAIZGIOo70QkWaWmLCIgb12mqIlU4fr9EDaaG7jj2ILHWMU5azYscIfrg
    BU3roSbgGbCRAoIBAQDYZarjPcB3SgHsIUsjk9Ls0nVge+wo+NXOXmzxsKplfQN4
    hyVJqxr0tfYWQtNLL1qwEqvetAIfQpMP85cEYvhgCLSf29AaSi6kClqwOlxcTEc/
    hTjCPjhp29Oj2z7D4xFKIo8gcdZnYkAusWc8hGZxtN+j6L6M4UCYUxi915TzM55M
    hIw/AlOhH81DvEOBnNHUi1V0ltW/KsGLd08SP7ApyxlNgq6u5jsNZQtFIMaHSv5y
    ubNJu69a2OwDthR77nJUGmq/BUbBJv8CcZLX7kXpUBEQ/beTKbEkGI0EHlQ5OhLb
    wBecoAoIQ240zoVjknaYzdkd5ZQnFyv74wBgKLshAoIBAQCjxHxEfPd6t92VQMpm
    pvcLL+Yu3vqVUGq7hq1Q/roaJR5jCNZwa3d2YrVhqS8P+IBJmVRNL/R7ao+0Uotm
    3ZsHPiRj8DiGMR/MDq+7EcHTizOLSrI6W02/ur1Pak5cHH3LrTdSbhw7GZtQf/Dv
    8R/YI7aUDGvvZtRmBgVqpIt2/BEeas4f8+zvdeJKv4kUqfraAwu9agR8F81Cr/dp
    8BUn0rCm7kF37LrUFfG6LwJzt8AbeB6ZiLCxP9TFJcqmV+5KiuIKM/rSElT4UyAh
    rllmHFGF/YaygxIqUsEwUW/FDcDMr3zBhpjckZ5lpUu7xHonsaCYlpv7dN2j5Q3f
    mM1hAoIBAFCYCFHg2LpxSeG2hQtj/kT5EydTl2Bpe5eZ+3evh6NxNVbbkkvkQZDo
    SvCHPYCTdBHtIDeFeFAm3CVBgA5rqXfli8eD4br/Ujy4eE4uoOEBDi8fsK3YIr8P
    jFt4LzU8DEYDoUWJNi37eS60K9AE+97MWMAOKpFtnPB//K3F+xA8gQg/ohMnBiOJ
    iwHFVi49tMW/ObOTJGmu7TKwqN/PShnTUqPi5gVn4XjUldrHfI7NMDI230kNqmSb
    b0WDwZwDEYjzwxm5GR/93OKfBa5x9r0h23jdzgJN0UP7uM/8Ntr3SFLx4+WYCqCS
    wgCQaIprVbpo7f92iiXrHSOJQ82AzAU=
    -----END PRIVATE KEY-----   

---

apiVersion: v1
kind: Service
metadata:
  name: secretapp
  namespace: secretapp
  labels:
    tier: secretapp
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    tier: secretapp

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: secretapp
  namespace: secretapp
spec:
  tls:
  - hosts:
      - secretapp.info
    secretName: secret-tls
  rules:
  - host: secretapp.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: secretapp
            port:
              number: 3000